## Reinstalling some modules 

In [8]:
import pandas as pd 
import matplotlib.pyplot as plt

import numpy as np
from sklearn import linear_model #from sklearn.linear_model import LinearRegression

In [6]:
import sys
print(sys.executable)
!type python

/Users/catherineng/Desktop/Python_Projects/PCA/pca/bin/python
python is /Users/catherineng/Desktop/Python_Projects/PCA/pca/bin/python


It seems like the Python in your path and the Python executable used in my notebook are the same. If they weren't, we wouldn't be able to use a simple !pip install or !conda install because it would install it in the  site-packages (folder where all your pip installed packages are) of the wrong Python installation. 

But just to be safe, we will install it with the workaround: !{sys.executable}  -m pip install pandas or !conda install --yes --prefix {sys.prefix} numpy

In [7]:
!{sys.executable}  -m pip install pandas

     |████████████████████████████████| 10.0MB 2.9MB/s eta 0:00:01    |███▊                            | 1.2MB 1.9MB/s eta 0:00:05
     |████████████████████████████████| 512kB 35.5MB/s eta 0:00:01
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
!pip install numpy

     |████████████████████████████████| 15.2MB 10.4MB/s eta 0:00:01   |                                | 30kB 1.6MB/s eta 0:00:10
You should consider upgrading via the 'pip install --upgrade pip' command.


In [5]:
!pip install matplotlib

  Using cached https://files.pythonhosted.org/packages/0d/61/b741990b429341bac1af5f5c645ee7aaa3bbe7daf3418d283c92c4b5ee82/matplotlib-3.2.1-cp37-cp37m-macosx_10_9_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/81/c5/9831f281c6fb57945e83fdf39ff036cacfdc84aa1988bb3150b330533050/kiwisolver-1.2.0-cp37-cp37m-macosx_10_9_x86_64.whl
You should consider upgrading via the 'pip install --upgrade pip' command.


In [7]:
!pip install -U scikit-learn

  Using cached https://files.pythonhosted.org/packages/64/57/23176044d9371e1af286176fd61cf7f74ed46d0b99122624ab93b3f32715/scikit_learn-0.22.2.post1-cp37-cp37m-macosx_10_9_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/85/7a/ae480be23b768910a9327c33517ced4623ba88dc035f9ce0206657c353a9/scipy-1.4.1-cp37-cp37m-macosx_10_6_intel.whl
You should consider upgrading via the 'pip install --upgrade pip' command.


## Linear Regression Model that you want to Download to Binary File

In [9]:
df = pd.read_csv('homeprices.csv')

In [13]:
model = linear_model.LinearRegression()

In [14]:
model.fit(df[['area']], df[['price']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
model.coef_ #calculates the coefficient, or m(slope)

model.intercept_ #calculates the intercept, or b

array([180616.43835616])

In [16]:
model.predict([[5000]]) #model calculated the value for m(slope) and b(intercept) [slope are also called coefficient]

array([[859554.79452055]])

## Using Pickle

In [17]:
import pickle #serialize your Python object into a file

In [18]:
#this will save a "model_pickle" file into your current local directory. 
with open('model_pickle', 'wb') as f: #will be writing binary data
    pickle.dump(model, f)

In [19]:
#Now you can load that specific file anytime you want to

with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [20]:
mp.predict([[5000]])

array([[859554.79452055]])

## Using JobLib
joblib is better at handling data with large numpy arrays internally. It can also take the file end directly (without using with open '')

In [23]:
import joblib

/Users/catherineng/Desktop/Python_Projects/PCA/pca/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [24]:
#like pickle, this will save a "model_joblib" file into your current local directory. 

joblib.dump(model, 'model_joblib')

['model_joblib']

In [25]:
#Now you can load that specific file anytime you want to

mj = joblib.load('model_joblib')

In [27]:
mj.predict([[5000]])

array([[859554.79452055]])